name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'sbt'
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck